import { Tutor } from "@/components/ui/TutorCard";

export const tutors: Tutor[] = [
  {
    id: "amina-nyerere",
    name: "Amina Nyerere",
    location: "Dar es Salaam, Tanzania",
    rating: 4.9,
    price: 18,
    languages: ["Kiswahili", "Business Swahili"],
    payments: ["cUSD", "CELO", "Fiat"],
    online: true,
    topTutor: true,
    bio: "Patient conversational coach helping founders, diplomats, and travelers speak confident Kiswahili with East African cultural fluency.",
  },
  {
    id: "brian-otieno",
    name: "Brian Otieno",
    location: "Nairobi, Kenya",
    rating: 4.8,
    price: 14,
    languages: ["Kiswahili", "Sheng"],
    payments: ["cUSD", "Fiat"],
    online: true,
    bio: "Nairobi-based tutor specializing in everyday Kiswahili, pronunciation, and modern Kenyan street expressions for real conversations.",
  },
  {
    id: "zawadi-mushi",
    name: "Zawadi Mushi",
    location: "Arusha, Tanzania",
    rating: 5.0,
    price: 25,
    languages: ["Kiswahili", "Tourism"],
    payments: ["cUSD", "CELO"],
    online: false,
    topTutor: true,
    bio: "Safari and hospitality language expert teaching polished Kiswahili for tourism teams, guides, and premium travel professionals.",
  },
  {
    id: "neema-kariuki",
    name: "Neema Kariuki",
    location: "Mombasa, Kenya",
    rating: 4.7,
    price: 12,
    languages: ["Kiswahili", "Coastal Dialect"],
    payments: ["CELO", "Fiat"],
    online: true,
    bio: "Warm coastal Kiswahili instructor with a focus on rhythm, greetings, food culture, and confidence for beginners.",
  },
  {
    id: "juma-mwinyi",
    name: "Juma Mwinyi",
    location: "Zanzibar, Tanzania",
    rating: 4.9,
    price: 20,
    languages: ["Kiswahili", "Culture"],
    payments: ["cUSD", "CELO", "Fiat"],
    online: false,
    bio: "Cultural storyteller and certified tutor blending grammar, island history, music, and practical speaking drills.",
  },
  {
    id: "faith-wanjala",
    name: "Faith Wanjala",
    location: "Kisumu, Kenya",
    rating: 4.6,
    price: 8,
    languages: ["Kiswahili", "Beginner"],
    payments: ["cUSD", "Fiat"],
    online: true,
    bio: "Friendly beginner specialist using games, flashcards, and short speaking challenges to make first lessons feel easy.",
  },
];

export const reviews = [
  { name: "Maya Chen", rating: 5, date: "May 12, 2026", comment: "Amina made Kiswahili feel elegant and practical. I booked three more sessions immediately." },
  { name: "Kwame Mensah", rating: 5, date: "May 8, 2026", comment: "Great structure, clear pronunciation coaching, and smooth cUSD checkout." },
  { name: "Elena Rossi", rating: 4.5, date: "Apr 29, 2026", comment: "The cultural context helped me prepare for work in Arusha with confidence." },
  { name: "Daniel Okafor", rating: 5, date: "Apr 21, 2026", comment: "Professional, warm, and very organized. Best online tutor experience I have had." },
];
