import { CalendarDays, DollarSign, Star, Users } from 'lucide-react'
import { Avatar } from '@/components/ui/Avatar'
import { Button } from '@/components/ui/Button'
import { Card } from '@/components/ui/Card'

const nav = ['Overview', 'My Sessions', 'Availability', 'Earnings', 'Profile', 'Settings']

export default function TutorDashboardPage() {
  return <main className="min-h-screen bg-off-white text-forest lg:pl-80"><aside className="fixed inset-y-0 left-0 hidden w-80 bg-forest p-6 text-cream lg:block"><h1 className="font-serif text-3xl font-black">Lugha<span className="text-gold">Pro</span></h1><nav className="mt-10 grid gap-2">{nav.map((item, index) => <a key={item} href="#" className={`rounded-2xl px-4 py-3 font-bold ${index === 0 ? 'bg-gold text-forest' : 'hover:bg-white/10'}`}>{item}</a>)}</nav></aside><section className="px-5 py-8 lg:px-10"><h1 className="font-serif text-5xl font-black">Habari, Tutor 👋</h1><p className="mt-2 text-forest/65">Your teaching studio is ready.</p><div className="mt-8 grid gap-4 md:grid-cols-4">{[[CalendarDays, 'Total Sessions', '0'], [Users, 'Students Taught', '0'], [DollarSign, 'Total Earned', '0 cUSD'], [Star, 'Rating', 'New']].map(([Icon, label, value]) => <Card key={String(label)}><Icon className="h-7 w-7 text-gold" /><p className="mt-4 text-sm font-bold text-forest/60">{label as string}</p><p className="mt-2 text-3xl font-black text-jade">{value as string}</p></Card>)}</div><div className="mt-8 grid gap-6 xl:grid-cols-2"><Card><h2 className="font-serif text-3xl font-black">Upcoming Sessions</h2><div className="mt-5 rounded-2xl bg-cream p-4"><div className="flex items-center gap-3"><Avatar name="Student" /><div><p className="font-bold">No sessions yet</p><p className="text-sm text-forest/60">Your upcoming lessons will appear here.</p></div></div></div></Card><Card><h2 className="font-serif text-3xl font-black">Earnings This Month</h2><p className="mt-5 text-5xl font-black text-jade">0 cUSD ↑</p><p className="mt-4 rounded-2xl bg-gold/15 p-4 text-sm font-bold text-forest">Crypto withdrawals coming soon.</p><Button className="mt-6">Withdraw Earnings</Button></Card></div><Card className="mt-8"><h2 className="font-serif text-3xl font-black">Set Your Availability</h2><div className="mt-5 grid gap-3 md:grid-cols-7">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map((day) => <div key={day} className="rounded-2xl bg-cream p-3"><p className="font-black">{day}</p><label className="mt-3 flex items-center gap-2 text-sm"><input type="checkbox" /> Available</label><input className="mt-3 w-full rounded-xl border p-2 text-xs" type="time" /><input className="mt-2 w-full rounded-xl border p-2 text-xs" type="time" /></div>)}</div><Button className="mt-5">Save Availability</Button></Card></section></main>
}
